CREATE TABLE IF NOT EXISTS guests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nom TEXT NOT NULL,
  categorie TEXT NOT NULL DEFAULT 'perso',
  save_the_date INTEGER NOT NULL DEFAULT 0,
  invitation INTEGER NOT NULL DEFAULT 0,
  a_repondu INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_guests_categorie ON guests(categorie);

INSERT INTO guests (nom, categorie, save_the_date, invitation, a_repondu, notes) VALUES
-- Famille
('Famille Ju', 'famille', 1, 1, 1, 'parents'),
('Famille Mathilde', 'famille', 1, 1, 1, NULL),
('Laura (soeur)', 'famille', 1, 1, 1, NULL),
('Famille Louis', 'famille', 1, 1, 1, NULL),
-- Perso
('Jasmin', 'perso', 1, 1, 0, NULL),
('Kenwa', 'perso', 1, 1, 0, NULL),
('Zitoun', 'perso', 1, 1, 0, NULL),
('Julien', 'perso', 1, 1, 0, NULL),
('Sarah', 'perso', 1, 1, 1, NULL),
('Camilo', 'perso', 1, 1, 1, NULL),
('Louisa', 'perso', 1, 1, 1, NULL),
('Guillaume', 'perso', 1, 1, 1, NULL),
('Anaïs', 'perso', 1, 1, 1, NULL),
('Laura', 'perso', 1, 1, 1, NULL),
('Clément', 'perso', 1, 1, 1, NULL),
('Mathilde', 'perso', 1, 1, 1, NULL),
('Alice', 'perso', 1, 1, 1, NULL),
('Carotte', 'perso', 1, 1, 1, NULL),
('Julie Rabier', 'perso', 1, 1, 1, NULL),
('Eliza', 'perso', 1, 1, 0, NULL),
('Manu', 'perso', 1, 1, 0, NULL),
('Fabienne et Régine', 'perso', 1, 1, 1, NULL),
('Laeti', 'perso', 1, 1, 0, NULL),
('Xav', 'perso', 1, 1, 0, NULL),
('Fabrice', 'perso', 1, 1, 0, NULL),
('Hadrien', 'perso', 1, 1, 0, NULL),
('Rémi', 'perso', 1, 1, 0, NULL),
('Sandrine', 'perso', 1, 1, 1, NULL),
('Florent', 'perso', 1, 1, 0, NULL),
('Antoine', 'perso', 1, 1, 0, NULL),
('Pako', 'perso', 1, 1, 0, NULL),
('Amélie', 'perso', 1, 1, 0, NULL),
('Antoine (2)', 'perso', 1, 1, 0, NULL),
('Apolline / Clo', 'perso', 1, 1, 1, NULL),
('Bérangère', 'perso', 1, 0, 0, NULL),
('Fred TH', 'perso', 1, 1, 0, NULL),
('Clément (2)', 'perso', 1, 1, 0, NULL),
('Léa', 'perso', 1, 1, 0, NULL),
('Alexandra et sa famille', 'perso', 1, 1, 0, NULL),
('Jojo', 'perso', 1, 1, 0, NULL),
('Harold', 'perso', 1, 1, 0, NULL),
('Claire', 'perso', 1, 1, 0, NULL),
('Léa Puyf', 'perso', 1, 1, 0, NULL),
('Lola', 'perso', 1, 1, 0, NULL),
('Marion', 'perso', 1, 1, 0, NULL),
('Nathy', 'perso', 1, 1, 0, NULL),
('Popo', 'perso', 1, 1, 0, NULL),
('Popo (2)', 'perso', 1, 1, 0, 'car des choix'),
('Brahim', 'perso', 1, 1, 0, NULL),
('Sonia', 'perso', 1, 1, 0, NULL),
('Arnaud', 'perso', 1, 1, 0, NULL),
('Anaïs (2)', 'perso', 1, 1, 0, NULL),
('Steph', 'perso', 1, 1, 1, NULL),
('Nico', 'perso', 1, 1, 1, NULL),
('Victor', 'perso', 1, 1, 0, NULL),
('Axel', 'perso', 1, 1, 0, NULL),
('Zoubir', 'perso', 1, 1, 0, NULL),
('Gilles et Sandrine', 'perso', 1, 1, 0, NULL),
('Patricia', 'perso', 1, 1, 1, NULL),
('Céline', 'perso', 1, 1, 0, NULL),
('Jo', 'perso', 1, 1, 0, NULL),
('G', 'perso', 1, 1, 0, NULL),
('Maud', 'perso', 1, 1, 0, NULL),
('Aurélie', 'perso', 1, 1, 0, NULL),
('Greg', 'perso', 1, 1, 0, NULL),
('Julien Batouk', 'perso', 1, 1, 0, NULL),
('Big Jul', 'perso', 1, 1, 1, NULL),
('Océane', 'perso', 1, 1, 0, NULL),
('Etienne (pote)', 'perso', 1, 1, 0, NULL),
('Laurie', 'perso', 1, 1, 0, NULL),
('Nico (2)', 'perso', 1, 1, 0, NULL),
('Guillaume (2)', 'perso', 1, 1, 0, NULL),
('Heri', 'perso', 1, 1, 0, NULL),
('Mathilde (2)', 'perso', 1, 1, 0, NULL),
('Benoît', 'perso', 1, 1, 0, NULL),
('Chanti', 'perso', 1, 1, 0, NULL),
('Melvyn', 'perso', 1, 1, 0, NULL),
-- Pro
('Bernard', 'pro', 0, 0, 0, 'échafaudage'),
('Pauline', 'pro', 1, 1, 0, 'CM'),
('Pierre Carli', 'pro', 1, 1, 0, NULL),
('Équipe chantiers', 'pro', 1, 1, 0, 'Antoine, Apolline, César, Guillaume Ferm, Laurent, Kevin, Quentin, Gabriel — voir mails chantiers'),
('Arnaud Vens', 'pro', 1, 1, 0, NULL),
('Catherine', 'pro', 1, 1, 1, NULL),
('Claire Bocéno', 'pro', 1, 1, 0, NULL),
('Fred & Catherine', 'pro', 1, 1, 1, NULL),
('Michel Augeard', 'pro', 1, 1, 1, NULL),
('Jacques et sa femme', 'pro', 1, 1, 1, NULL),
('Marine Rosalie', 'pro', 1, 1, 1, NULL),
('Nico ingé son', 'pro', 1, 1, 0, 'ingénieur son'),
('Etienne Pradal', 'pro', 1, 1, 0, NULL),
('Pascal', 'pro', 1, 1, 1, NULL),
('Lydie', 'pro', 1, 1, 1, NULL),
('Eric Berrias', 'pro', 1, 1, 0, 'métal service'),
('Lucie Penellon', 'pro', 1, 1, 1, NULL),
('Julie Petite Maison', 'pro', 1, 1, 0, NULL),
('Mathieu', 'pro', 1, 1, 1, 'voisin — sud sécurité'),
('Chloé Mouraret', 'pro', 1, 1, 0, 'CIC'),
('Marie-Ophélie', 'pro', 1, 1, 0, NULL),
('Nicolas Klee', 'pro', 1, 1, 0, NULL),
('Clémentine Chung', 'pro', 1, 1, 0, NULL),
('Flore Vigne', 'pro', 1, 1, 0, NULL),
-- Voisins
('Martine', 'voisins', 1, 1, 0, NULL),
('Eric Marchial', 'voisins', 1, 1, 0, NULL),
('Jean-Marc Pertus', 'voisins', 1, 1, 1, NULL),
('Rocheyrol', 'voisins', 1, 1, 1, NULL),
('Jérôme Vernède', 'voisins', 1, 1, 0, NULL),
('Savannah et Kevin', 'voisins', 1, 1, 1, NULL),
('Laurence Foussac', 'voisins', 1, 1, 0, NULL),
('Chataigneraie', 'voisins', 0, 0, 0, NULL),
('Mas du Serre', 'voisins', 0, 0, 0, NULL),
-- Élus
('Monique', 'elus', 1, 1, 0, NULL),
('Fabien', 'elus', 1, 1, 0, NULL),
('Marie-Jo', 'elus', 1, 1, 0, NULL),
('Sylvie', 'elus', 1, 1, 0, NULL),
('Mec mairie', 'elus', 1, 1, 0, NULL),
('Julie', 'elus', 1, 1, 0, NULL),
('Sandrine accueil', 'elus', 1, 1, 0, NULL),
-- Presse
('Philippe', 'presse', 1, 1, 1, NULL),
-- À confirmer
('Hiba Hsayki', 'autre', 0, 0, 0, NULL),
('Benoit Michel', 'autre', 0, 0, 0, NULL),
('Maires communes alentour', 'autre', 0, 0, 0, NULL),
('Département', 'autre', 0, 0, 0, NULL),
('Région', 'autre', 0, 0, 0, NULL),
('Comcom', 'autre', 0, 0, 0, NULL),
('Office de tourisme', 'autre', 0, 0, 0, NULL);
